name: vancouver
channels:
  - defaults
  - conda-forge
dependencies:
  - dash=0.34.0
  - dash-core-components=0.42.0
  - dash-html-components=0.13.4
  - dash-renderer=0.16.1
  - dash-table=3.1.11
  - flask-compress=1.4.0
  - asn1crypto=0.24.0
  - babel=2.6.0
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.4.2
  - decorator=4.3.0
  - flask=1.0.2
  - idna=2.8
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_core=4.4.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - markupsafe=1.1.0
  - nbformat=4.4.0
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=18.1
  - plotly=3.4.2
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.7.2
  - pytz=2018.7
  - readline=7.0
  - requests=2.21.0
  - retrying=1.3.3
  - setuptools=40.6.3
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - traitlets=4.3.2
  - urllib3=1.24.1
  - waitress=1.2.0
  - werkzeug=0.14.1
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11

